x-healthcheck-parameters: &healthcheck-parameters
  interval: 30s
  timeout: 10s
  start_period: 30s
  retries: 3

x-environment-defaults: &environment-defaults
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

services:
  bittorrent:
    container_name: bittorrent
    image: lscr.io/linuxserver/qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - /docker/bittorrent/config:/config:rw
      - downloads:/downloads:rw
    environment:
      <<: *environment-defaults
      WEBUI_PORT: 8088
    healthcheck:
      test: curl -fsS localhost:8088/api/v2/app/version
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.bittorrent.entrypoints=websecure
      - traefik.http.services.bittorrent.loadbalancer.server.port=8088
    depends_on:
      gluetun:
        condition: service_healthy

  bittorrent-port-forward-gluetun:
    container_name: bittorrent-port-forward-gluetun
    image: mjmeli/qbittorrent-port-forward-gluetun-server
    restart: unless-stopped
    volumes:
      - /docker/bittorrent_port_forward_gluetun/config:/config:rw
    environment:
      QBT_ADDR: http://gluetun:8088
      GTN_ADDR: http://gluetun:8000
      GTN_APIKEY: ${GTN_APIKEY}
    depends_on:
      bittorrent:
        condition: service_healthy

  cleanuparr:
    container_name: cleanuparr
    image: ghcr.io/cleanuparr/cleanuparr
    restart: unless-stopped
    volumes:
      - /docker/cleanuparr/config:/config:rw
      - downloads:/downloads:rw
    environment:
      <<: *environment-defaults
    healthcheck:
      test: curl -fsS localhost:11011/health
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.cleanuparr.entrypoints=websecure
      - traefik.http.services.cleanuparr.loadbalancer.server.port=11011
    depends_on:
      bittorrent:
        condition: service_healthy