services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    restart: unless-stopped
    volumes:
      - /docker/vaultwarden/app:/data:rw
    environment:
      DOMAIN: https://vwarden.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80

networks:
  default:
    name: proxy_network
    external: true
