x-healthcheck-parameters: &healthcheck-parameters
  interval: 30s
  timeout: 10s
  start_period: 30s
  retries: 3

x-environment-defaults: &environment-defaults
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

services:
  gitea:
    container_name: gitea
    image: docker.gitea.com/gitea
    restart: unless-stopped
    ports:
      - 1122:22/tcp
    networks:
      - proxy
      - private
    volumes:
      - /docker/gitea/app:/data:rw
    environment:
      <<: *environment-defaults
      GITEA__server__DOMAIN: git.${DOMAIN}
      GITEA__server__SSH_DOMAIN: git.${DOMAIN}
      GITEA__server__ROOT_URL: https://git.${DOMAIN}/
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: database:5432
      GITEA__database__USER: ${POSTGRES_USER}
      GITEA__database__PASSWD: ${POSTGRES_PASSWORD}
      GITEA__database__NAME: ${POSTGRES_DB}
      GITEA__security__SECRET_KEY: ${SECRET_KEY}
      GITEA__security__INTERNAL_TOKEN: ${INTERNAL_TOKEN}
    healthcheck:
      test: wget -qO- --tries=1 http://localhost:3000/api/healthz
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.rule=Host(`git.${DOMAIN}`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: gitea-database
    image: postgres
    restart: unless-stopped
    networks:
      - private
    volumes:
      - /docker/gitea/database:/var/lib/postgresql:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
      <<: *healthcheck-parameters

networks:
  private:
    name: gitea_network
    internal: true
  proxy:
    name: proxy_network
    external: true
