x-healthcheck-parameters: &healthcheck-parameters
  interval: 30s
  timeout: 10s
  start_period: 30s
  retries: 3

services:
  traefik:
    container_name: traefik
    image: traefik:v3
    restart: unless-stopped
    command: --configFile=/config/traefik.yml
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt:rw
      - ./config:/config:ro
    environment:
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
    healthcheck:
      test: traefik healthcheck --ping
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${DASHBOARD_CREDENTIALS}

volumes:
  letsencrypt:

networks:
  default:
    name: proxy_network
    ipam:
      config:
        - subnet: 172.16.0.0/16
