routers:
  synology:
    rule: Host(`synology.doesmyserver.work`)
    service: synology
    middlewares:
      - secure-headers@middleware
      - compress@middleware

services:
  synology:
    loadBalancer:
      servers:
        - url: https://192.168.1.90:5080
      passHostHeader: true