http:
  middlewares:
    dashboard-auth:
      basicAuth:
        users:
        # use htpasswd to generate the password
        # htpasswd -nb admin <password>
          - "admin:password"

    secure-headers:
      headers:
        contentTypeNosniff: true
        contentSecurityPolicy: "default-src 'self'"
        referrerPolicy: "strict-origin-when-cross-origin"
        forceSTSHeader: true
        frameDeny: false
        customResponseHeaders:
          Server: false
          Via: false
          X-Powered-By: false
          X-Forwarded-Proto: "https"

    compress:
      compress: