x-healthcheck-parameters: &healthcheck-parameters
  interval: 30s
  timeout: 10s
  start_period: 30s
  retries: 3

x-environment-defaults: &environment-defaults
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - /docker/sonarr/config:/config:rw
      - media:/mnt/media:rw
      - downloads:/downloads:rw
    environment:
      <<: *environment-defaults
    healthcheck:
      test: curl -fsS localhost:8989/ping
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    depends_on:
      gluetun:
        condition: service_healthy

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - /docker/radarr/config:/config:rw
      - media:/mnt/media:rw
      - downloads:/downloads:rw
    environment:
      <<: *environment-defaults
    healthcheck:
      test: curl -fsS localhost:7878/ping
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    depends_on:
      gluetun:
        condition: service_healthy
    
  profilarr:
    container_name: profilarr
    image: ghcr.io/dictionarry-hub/profilarr
    restart: unless-stopped
    volumes:
      - /docker/profilarr/config:/config:rw
    environment:
      <<: *environment-defaults
      ORIGIN: https://profilarr.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.profilarr.entrypoints=websecure
      - traefik.http.services.profilarr.loadbalancer.server.port=6868
    depends_on:
      sonarr:
        condition: service_healthy
      radarr:
        condition: service_healthy

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - /docker/prowlarr/config:/config:rw
    environment:
      <<: *environment-defaults
    healthcheck:
      test: curl -fsS localhost:9696/ping
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    depends_on:
      gluetun:
        condition: service_healthy

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - /docker/flaresolverr/config:/config:rw
    environment:
      TZ: ${TZ}
      LOG_LEVEL: debug
      DISABLE_MEDIA: true
    healthcheck:
      test: curl -fsS localhost:8191/health
      <<: *healthcheck-parameters
    depends_on:
      gluetun:
        condition: service_healthy
      prowlarr:
        condition: service_healthy