x-healthcheck-parameters: &healthcheck-parameters
  interval: 30s
  timeout: 10s
  start_period: 30s
  retries: 3

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 7359:7359/udp
    volumes:
      - /docker/jellyfin/config:/config:rw
      - jellyfin_cache:/cache:rw
      - media:/mnt/media:rw
    environment:
      JELLYFIN_PublishedServerUrl: https://jellyfin.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.services.jellyfin.loadbalancer.responseforwarding.flushinterval=-1

  seerr:
    container_name: seerr
    image: seerr/seerr
    restart: unless-stopped
    init: true
    volumes:
      - /docker/seerr/config:/app/config:rw
    environment:
      TZ: ${TZ}
    healthcheck:
      test: wget -qO- --tries=1 http://localhost:5055/api/v1/status
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.seerr.entrypoints=websecure
      - traefik.http.services.seerr.loadbalancer.server.port=5055
    depends_on:
      jellyfin:
        condition: service_healthy
      sonarr:
        condition: service_healthy
      radarr:
        condition: service_healthy

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /docker/gluetun:/gluetun:rw
      - ./config:/gluetun/auth:ro
    environment:
      TZ: ${TZ}
      UPDATER_PERIOD: 24h
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      VPN_TYPE: wireguard
      VPN_PORT_FORWARDING: on
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      DNS_UPSTREAM_RESOLVERS: cloudflare,google

include:
  - arr-compose.yml
  - torrent-compose.yml

volumes:
  jellyfin_cache:
  downloads:
  media:
    name: servarr_smb_media
    driver: local
    driver_opts:
      type: cifs
      device: //${SMB_HOST}/${SMB_SHARE}
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,rw,noatime,uid=${PUID},gid=${PGID}

networks:
  default:
    name: proxy_network
    external: true