x-healthcheck-parameters: &healthcheck-parameters
  interval: 30s
  timeout: 10s
  start_period: 30s
  retries: 3

services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy
    restart: unless-stopped
    command: serve
    init: true
    networks:
      - proxy
      - private
    volumes:
      - cache:/var/cache/ntfy:rw
    environment:
      TZ: ${TZ}
      NTFY_BASE_URL: https://ntfy.${DOMAIN}
      NTFY_LISTEN_HTTP: :2586
      NTFY_BEHIND_PROXY: true
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
      NTFY_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_ENABLE_LOGIN: true
      NTFY_REQUIRE_LOGIN: true
      NTFY_AUTH_USERS: ${NTFY_AUTH_USERS}
      NTFY_AUTH_TOKENS: ${NTFY_AUTH_TOKENS}
      NTFY_AUTH_ACCESS: ${NTFY_AUTH_ACCESS}
    healthcheck:
      test: wget -qO- --tries=1 http://localhost:2586/v1/health
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.ntfy.entrypoints=websecure
      - traefik.http.services.ntfy.loadbalancer.server.port=2586
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: ntfy-database
    image: postgres
    restart: unless-stopped
    networks:
      - private
    volumes:
      - /docker/ntfy/database:/var/lib/postgresql:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
      <<: *healthcheck-parameters

volumes:
  cache:

networks:
  private:
    name: ntfy_network
    internal: true
  proxy:
    name: proxy_network
    external: true
