x-healthcheck-parameters: &healthcheck-parameters
  interval: 30s
  timeout: 10s
  start_period: 30s
  retries: 3

services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng
    restart: unless-stopped
    networks:
      - proxy
      - private
    volumes:
      - ./config:/etc/searxng:ro
      - cache:/var/cache/searxng:rw
    environment:
      SEARXNG_SECRET: ${SEARXNG_SECRET}
      SEARXNG_BASE_URL: https://searxng.${DOMAIN}
    healthcheck:
      test: wget -qO- --tries=1 http://localhost:8080/healthz
      <<: *healthcheck-parameters
    labels:
      - traefik.enable=true
      - traefik.http.routers.searxng.entrypoints=websecure
      - traefik.http.services.searxng.loadbalancer.server.port=8080
    depends_on:
      valkey:
        condition: service_healthy

  valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey
    restart: unless-stopped
    command: valkey-server --save 60 1 --loglevel debug
    networks:
      - private
    volumes:
      - /docker/searxng/valkey/config:/etc/valkey:rw
      - /docker/searxng/valkey/data:/data:rw
    healthcheck:
      test: valkey-cli ping
      <<: *healthcheck-parameters

volumes:
  cache:

networks:
  private:
    name: searxng_network
    internal: true
  proxy:
    name: proxy_network
    external: true
